FROM nginx:alpine

# Copiamos la configuración que le dice a Nginx cómo manejar las rutas de Angular
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiamos los archivos compilados
COPY dist/music/browser /usr/share/nginx/html

EXPOSE 80